// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Nexus.Data.Persistence;

#nullable disable

namespace Nexus.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260531001000_AddAcademicModels")]
partial class AddAcademicModels
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("nexus")
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
        {
            b.Property<string>("Id").HasColumnType("nvarchar(450)");
            b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
            b.Property<string>("Name").HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.HasKey("Id");
            b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex").HasFilter("[NormalizedName] IS NOT NULL");
            b.ToTable("AspNetRoles", "nexus");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
            b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
            b.Property<string>("RoleId").IsRequired().HasColumnType("nvarchar(450)");
            b.HasKey("Id");
            b.HasIndex("RoleId");
            b.ToTable("AspNetRoleClaims", "nexus");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
            b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
            b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
            b.HasKey("Id");
            b.HasIndex("UserId");
            b.ToTable("AspNetUserClaims", "nexus");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
        {
            b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
            b.Property<string>("ProviderKey").HasColumnType("nvarchar(450)");
            b.Property<string>("ProviderDisplayName").HasColumnType("nvarchar(max)");
            b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
            b.HasKey("LoginProvider", "ProviderKey");
            b.HasIndex("UserId");
            b.ToTable("AspNetUserLogins", "nexus");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
        {
            b.Property<string>("UserId").HasColumnType("nvarchar(450)");
            b.Property<string>("RoleId").HasColumnType("nvarchar(450)");
            b.HasKey("UserId", "RoleId");
            b.HasIndex("RoleId");
            b.ToTable("AspNetUserRoles", "nexus");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
        {
            b.Property<string>("UserId").HasColumnType("nvarchar(450)");
            b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
            b.Property<string>("Name").HasColumnType("nvarchar(450)");
            b.Property<string>("Value").HasColumnType("nvarchar(max)");
            b.HasKey("UserId", "LoginProvider", "Name");
            b.ToTable("AspNetUserTokens", "nexus");
        });

        modelBuilder.Entity("Nexus.Data.Identity.ApplicationUser", b =>
        {
            b.Property<string>("Id").HasColumnType("nvarchar(450)");
            b.Property<int>("AccessFailedCount").HasColumnType("int");
            b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
            b.Property<string>("DisplayName").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("Email").HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<bool>("EmailConfirmed").HasColumnType("bit");
            b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<bool>("LockoutEnabled").HasColumnType("bit");
            b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("datetimeoffset");
            b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<string>("PasswordHash").HasColumnType("nvarchar(max)");
            b.Property<string>("PhoneNumber").HasColumnType("nvarchar(max)");
            b.Property<bool>("PhoneNumberConfirmed").HasColumnType("bit");
            b.Property<string>("SecurityStamp").HasColumnType("nvarchar(max)");
            b.Property<bool>("TwoFactorEnabled").HasColumnType("bit");
            b.Property<string>("UserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.HasKey("Id");
            b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
            b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex").HasFilter("[NormalizedUserName] IS NOT NULL");
            b.ToTable("AspNetUsers", "nexus");
        });


        modelBuilder.Entity("Nexus.Data.Models.Department", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
            b.HasKey("Id");
            b.HasIndex("Name").IsUnique();
            b.ToTable("Departments", "nexus");
        });

        modelBuilder.Entity("Nexus.Data.Models.Course", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<int?>("DepartmentId").HasColumnType("int");
            b.Property<string>("Name").IsRequired().HasMaxLength(160).HasColumnType("nvarchar(160)");
            b.Property<string>("Semester").IsRequired().HasMaxLength(60).HasColumnType("nvarchar(60)");
            b.Property<string>("TeacherId").IsRequired().HasMaxLength(450).HasColumnType("nvarchar(450)");
            b.HasKey("Id");
            b.HasIndex("DepartmentId");
            b.HasIndex("TeacherId");
            b.HasIndex("Name", "Semester").IsUnique();
            b.ToTable("Courses", "nexus");
        });

        modelBuilder.Entity("Nexus.Data.Models.Assignment", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<int>("CourseId").HasColumnType("int");
            b.Property<DateTime>("Deadline").HasColumnType("datetime2");
            b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
            b.Property<string>("Title").IsRequired().HasMaxLength(180).HasColumnType("nvarchar(180)");
            b.HasKey("Id");
            b.HasIndex("CourseId", "Deadline");
            b.ToTable("Assignments", "nexus");
        });

        modelBuilder.Entity("Nexus.Data.Models.Enrollment", b =>
        {
            b.Property<string>("StudentId").HasMaxLength(450).HasColumnType("nvarchar(450)");
            b.Property<int>("CourseId").HasColumnType("int");
            b.HasKey("StudentId", "CourseId");
            b.HasIndex("CourseId");
            b.ToTable("Enrollments", "nexus");
        });

        modelBuilder.Entity("Nexus.Data.Models.Grade", b =>
        {
            b.Property<string>("StudentId").HasMaxLength(450).HasColumnType("nvarchar(450)");
            b.Property<int>("CourseId").HasColumnType("int");
            b.Property<decimal>("AssignmentMarks").HasPrecision(5, 2).HasColumnType("decimal(5,2)");
            b.Property<decimal>("FinalMarks").HasPrecision(5, 2).HasColumnType("decimal(5,2)");
            b.Property<decimal>("MidtermMarks").HasPrecision(5, 2).HasColumnType("decimal(5,2)");
            b.Property<decimal>("TotalMarks").HasPrecision(5, 2).HasColumnType("decimal(5,2)");
            b.HasKey("StudentId", "CourseId");
            b.HasIndex("CourseId");
            b.ToTable("Grades", "nexus");
        });

        modelBuilder.Entity("Nexus.Data.Models.Submission", b =>
        {
            b.Property<string>("StudentId").HasMaxLength(450).HasColumnType("nvarchar(450)");
            b.Property<int>("AssignmentId").HasColumnType("int");
            b.Property<string>("FilePath").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<DateTime>("SubmittedAt").HasColumnType("datetime2");
            b.HasKey("StudentId", "AssignmentId");
            b.HasIndex("AssignmentId");
            b.ToTable("Submissions", "nexus");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
        {
            b.HasOne("Nexus.Data.Identity.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
        {
            b.HasOne("Nexus.Data.Identity.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("Nexus.Data.Identity.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
        {
            b.HasOne("Nexus.Data.Identity.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("Nexus.Data.Models.Course", b =>
        {
            b.HasOne("Nexus.Data.Models.Department", "Department").WithMany("Courses").HasForeignKey("DepartmentId").OnDelete(DeleteBehavior.SetNull);
            b.HasOne("Nexus.Data.Identity.ApplicationUser", "Teacher").WithMany().HasForeignKey("TeacherId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            b.Navigation("Department");
            b.Navigation("Teacher");
        });

        modelBuilder.Entity("Nexus.Data.Models.Assignment", b =>
        {
            b.HasOne("Nexus.Data.Models.Course", "Course").WithMany("Assignments").HasForeignKey("CourseId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("Course");
        });

        modelBuilder.Entity("Nexus.Data.Models.Enrollment", b =>
        {
            b.HasOne("Nexus.Data.Models.Course", "Course").WithMany("Enrollments").HasForeignKey("CourseId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("Nexus.Data.Identity.ApplicationUser", "Student").WithMany().HasForeignKey("StudentId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("Course");
            b.Navigation("Student");
        });

        modelBuilder.Entity("Nexus.Data.Models.Grade", b =>
        {
            b.HasOne("Nexus.Data.Models.Course", "Course").WithMany("Grades").HasForeignKey("CourseId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("Nexus.Data.Identity.ApplicationUser", "Student").WithMany().HasForeignKey("StudentId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("Course");
            b.Navigation("Student");
        });

        modelBuilder.Entity("Nexus.Data.Models.Submission", b =>
        {
            b.HasOne("Nexus.Data.Models.Assignment", "Assignment").WithMany("Submissions").HasForeignKey("AssignmentId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("Nexus.Data.Identity.ApplicationUser", "Student").WithMany().HasForeignKey("StudentId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("Assignment");
            b.Navigation("Student");
        });

        modelBuilder.Entity("Nexus.Data.Models.Assignment", b => b.Navigation("Submissions"));
        modelBuilder.Entity("Nexus.Data.Models.Course", b =>
        {
            b.Navigation("Assignments");
            b.Navigation("Enrollments");
            b.Navigation("Grades");
        });
        modelBuilder.Entity("Nexus.Data.Models.Department", b => b.Navigation("Courses"));

#pragma warning restore 612, 618
    }

}
