// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Nexus.Data.Persistence;

#nullable disable

namespace Nexus.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260531002000_AddTeacherStudentGradeQuizModules")]
partial class AddTeacherStudentGradeQuizModules
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        ApplicationDbContextModelSnapshot.BuildModel(modelBuilder);
#pragma warning restore 612, 618
    }
}
