// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Nexus.Data.Persistence;

#nullable disable

namespace Nexus.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260531130000_AddRepositoryAiAnalyticsFields")]
partial class AddRepositoryAiAnalyticsFields
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        ApplicationDbContextModelSnapshot.BuildModelStatic(modelBuilder);
#pragma warning restore 612, 618
    }
}
